import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { BookHeart, UsersRound } from 'lucide-react-native';
import { Screen } from '@/components/screen';
import { Button, EmptyState, ErrorState, Field, PaperCard } from '@/components/ui';
import { FriendTagPicker } from '@/components/friend-tag-picker';
import { api, apiCached, getCachedApiData, invalidateApiCache } from '@/lib/api';
import { border, colors, type } from '@/lib/theme';
import type { Friend, JournalNote } from '@/types';

const JOURNAL_PATH = '/api/diary';
const FRIENDS_PATH = '/api/friends';

export default function JournalScreen() {
  const cachedNotes = getCachedApiData<JournalNote[]>(JOURNAL_PATH);
  const [notes, setNotes] = useState<JournalNote[]>(cachedNotes || []); const [friends, setFriends] = useState<Friend[]>(() => getCachedApiData<Friend[]>(FRIENDS_PATH) || []); const [selectedFriendIds, setSelectedFriendIds] = useState<string[]>([]); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(!cachedNotes); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (force = false) => { if (!getCachedApiData(JOURNAL_PATH)) setLoading(true); setError(''); try { setNotes(await apiCached<JournalNote[]>(JOURNAL_PATH, { force })); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load your journal.'); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { load(); apiCached<Friend[]>(FRIENDS_PATH).then((items) => { setFriends(items); setSelectedFriendIds((current) => current.filter((id) => items.some((friend) => friend.id === id))); }).catch(() => {}); }, [load]));
  async function save() { if (!content.trim()) return Alert.alert('Write one honest line', 'Your journal entry needs a little something to hold.'); setSaving(true); try { await api('/api/diary', { method: 'POST', body: JSON.stringify({ title, content, friendIds: selectedFriendIds }) }); invalidateApiCache(JOURNAL_PATH); setTitle(''); setContent(''); setSelectedFriendIds([]); setOpen(false); await load(true); } catch (e) { Alert.alert('Entry not saved', e instanceof Error ? e.message : 'Try again.'); } finally { setSaving(false); } }
  return <Screen title="Journal" eyebrow="Private by default"><View style={styles.prompt}><View style={styles.promptIcon}><BookHeart size={23} color={colors.ink} /></View><View style={{ flex: 1 }}><Text style={styles.promptKicker}>A note for you</Text><Text style={styles.promptText}>What did today show you about the people you love?</Text></View></View><Button label={open ? 'Close entry' : 'Write today’s note'} tone="citrus" onPress={() => setOpen(!open)} />{open ? <PaperCard style={{ gap: 14 }}><Field label="Title (optional)" value={title} onChangeText={setTitle} placeholder="A small realization" /><Field label="Your note" value={content} onChangeText={setContent} multiline placeholder="Today I noticed…" /><View style={styles.tagSection}><Text style={styles.tagLabel}>People in this note <Text style={styles.optional}>Optional</Text></Text><FriendTagPicker friends={friends} selectedIds={selectedFriendIds} onChange={setSelectedFriendIds} multiple emptyLabel="Just me" helper="Choose any friends mentioned here, or keep the note untagged. Journal notes stay private." /></View><Button label="Keep it private" loading={saving} onPress={save} /></PaperCard> : null}
    {loading ? <ActivityIndicator color={colors.ink} style={{ marginVertical: 40 }} /> : error ? <ErrorState message={error} onRetry={load} /> : notes.length ? notes.map((note, index) => <PaperCard key={note.id} style={{ backgroundColor: [colors.white, '#E4E7FF', '#FFF2C9'][index % 3] }}><Text style={styles.date}>{new Date(note.createdAt).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</Text><Text style={styles.title}>{note.title || 'Untitled note'}</Text><Text style={styles.content}>{note.content}</Text>{note.friends?.length ? <View style={styles.taggedPeople}><UsersRound size={14} color={colors.muted} /><Text style={styles.taggedPeopleText}>{note.friends.map((friend) => friend.name).join(', ')}</Text></View> : null}{note.analysis ? <View style={styles.reflection}><Text style={styles.reflectionLabel}>Gentle reflection</Text><Text numberOfLines={4} style={styles.reflectionText}>{note.analysis}</Text></View> : null}</PaperCard>) : <EmptyState title="A blank page, in a good way" body="Journal notes are for the feelings around a memory—the part that only needs to belong to you." />}
  </Screen>;
}

const styles = StyleSheet.create({ prompt: { flexDirection: 'row', gap: 12, backgroundColor: colors.periwinkle, borderRadius: 18, padding: 16, ...border }, promptIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.citrus, alignItems: 'center', justifyContent: 'center', ...border }, promptKicker: { fontFamily: type.heavy, color: colors.periwinkleDark, fontSize: 10, letterSpacing: 1.2, textTransform: 'uppercase' }, promptText: { fontFamily: type.heavy, color: colors.ink, fontSize: 17, lineHeight: 23, marginTop: 3 }, tagSection: { gap: 8 }, tagLabel: { fontFamily: type.heavy, color: colors.ink, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1 }, optional: { fontFamily: type.medium, color: colors.muted, fontSize: 10, letterSpacing: .5 }, date: { fontFamily: type.heavy, color: colors.periwinkleDark, textTransform: 'uppercase', fontSize: 10, letterSpacing: 1 }, title: { fontFamily: type.heavy, color: colors.ink, fontSize: 19, marginTop: 6 }, content: { fontFamily: type.regular, color: colors.ink, fontSize: 15, lineHeight: 23, marginTop: 5 }, taggedPeople: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10 }, taggedPeopleText: { flex: 1, fontFamily: type.medium, color: colors.muted, fontSize: 12 }, reflection: { marginTop: 13, borderTopWidth: 1.5, borderTopColor: colors.line, paddingTop: 10 }, reflectionLabel: { fontFamily: type.heavy, color: colors.muted, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 }, reflectionText: { fontFamily: type.regular, color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 4 }, });
